pypi:
    script:
        - cp /keys/.pypirc ~/.pypirc
        - virtualenv env
        - source env/bin/activate
        - XDG_CACHE_HOME=/cache pip3 install -U pip wheel setuptools twine build
        - python -m build
        - twine check dist/*
        - twine upload dist/*
    tags:
        - python3
    only:
        - pypi
    artifacts:
        paths:
            - dist/
